### ISSUE TITLE
引入vite的PluginOption类型后，build命令报错

### ISSUE THREAD

**Issue by GGGLHHH** [antfu/ts-starter#99]
### Describe the bug

<img width="1103" alt="image" src="https://github.com/antfu/starter-ts/assets/58617090/cb7b877a-a656-43c8-a2e4-078c4551ea75">

### Reproduction

一旦使用PluginOption类型之后，打包报错

### System Info

```Shell
import type { PluginOption } from 'vite'

export const one = 1
export const two = 2

export type { PluginOption }
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
把 vite 放到 dependencies 或者 peerDependencies
